### ISSUE TITLE
Wielkość okna aplikacji

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#10]
Aplikacja powinna mieć mniejszą "wysokość" na tablecie 7" z Windows, nie da sie jej używać, dolna i górna cześć wychodzi poza ekran

**Comment by tendersoft-mjb** [comment]
Na zwykłym desktopie, przy wysokiej rozdzielczości jest podobnie - okno jest za małe i ucina tekst na dole, ale nie ma możliwości ani przewinięcia tekstu w dół, ani zmiany rozmiaru okna. 

![2019-03-11 (2)](https://user-images.githubusercontent.com/7294417/54136884-e0097500-441c-11e9-8354-d491b6b2f5b7.png)

Aplikacja powinna mieć określony minimalny rozmiar + powinno się dać ją dowolnie rozciągnąć.

Tam, gdzie tekst się nie mieści automatycznie powinny pojawiać się scrolle - najczęściej vertical scroll - horizontal tylko tam, gdzie to absolutnie konieczne.
