### ISSUE TITLE
Dodać info o Capslock

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#11]
pRZY TWORZENIU HASŁA    DODAĆ OSTRZERZENIE ŻE CAPSlOCK JEST WCIŚNIĘTY

**Comment by tendersoft-mjb** [comment]
Tu przykład jak to zaimplementować czytelnie i przy minimalnym wysiłku.

![](https://raw.githubusercontent.com/codeframework/docs/master/Caps-Lock%20Warning%20and%20Global%20Key%20Handlers/Caps-Lock%20Warning%20and%20Global%20Key%20Handlers.jpg)
src: https://goo.gl/images/SPuz22

**Comment by Fl4reTobiasH** [comment]
DODAJ JESZCZE W INNYCH MIEJSCACH GDZIE JEST WPISYWANE HASŁO
