### ISSUE TITLE
aktualizator powinien zamykać proces nanopow

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#17]
aktualizator powinien zamykać proces nanopow, inaczej niegdy nie będzie się aktualizował ponieważ uruchomiony nie będzie mógł być nadpisany

**Comment by tendersoft-mjb** [comment]
Ważne żeby nie było wycieku zasobów przy zabijaniu tego procesu.

Koszernie robi się to tak, że proces sam ma jakąś funkcję/flagę, która można wywołać zdalnie, a którą on sam co jakiś czas sprawdza i w razie aktywacji kończy pracę.
