### ISSUE TITLE
Zmiana lokalizacji instalacji programu

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#18]
Lokalizacja obecna: %appdata%/hodlertech sprawa że jest syf w plikach, katalog instalacyjny programu musi być inny: %appdata/hodlertech/HODLERWallet/

**Comment by DanielMazurFL4RE** [comment]
Dałem tak jak mowilem na telco, %appdata%/hodlertech/bin
