### ISSUE TITLE
musi się pokazywać powiadomienie o dostępnej nowej wersji systemu operacyjnego

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#2]

**Comment by DanielMazurFL4RE** [comment]
Pojawia sie gdy Android wykryje, robi to co jakis czas, na pewno przy ponownym uruchomieniu sprawdza

**Comment by Fl4reTobiasH** [comment]
@DanielMazurFL4RE  Chodzi o powiadomienie widoczne z poziomu portfela, np. na pasku powiadomień androida. Teraz pokazuje sie tylko po wejściu w aktualizację.
