### ISSUE TITLE
Opcja Share obsługuje tylko adresy Legacy a nie ten który wybraliśmy

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#26]
Jeśli wybierzemy w GUI adres np. Segwit, powinien on być przekazywany opcją share. W tym momencie niezależnie od wyboru użytkownika, zawsze jest przesyłany adres Legacy

**Comment by DanielMazurFL4RE** [comment]
procedure TfrmHome.ShowShareSheetAction1BeforeExecute(Sender: TObject);
begin
  ShowShareSheetAction1.TextMessage := receiveAddress.Text;
end;
