### ISSUE TITLE
Automatic fee - problem

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#27]
Po otwarciu portfela i wejściu w kartę wysyłki, pokazuje się pierwsze fee: 

![image](https://user-images.githubusercontent.com/45454639/54113798-5ee4ba80-43e9-11e9-8626-ee923db59d9e.png)

Po przejściu do fixed i powrocie do automatic, fee zmienia się na zupełnie inne

https://im2.ezgif.com/tmp/ezgif-2-85662dab3cea.gif

**Comment by DanielMazurFL4RE** [comment]
procedure TfrmHome.PerByteFeeEditChangeTracking(Sender: TObject);
var
  temp: BigInteger;
  decimals: Integer;
  b: BigInteger;
begin
  temp := 180 * (length(CurrentCoin.UTXO)) + 2 * 34 + 10 + 2;

powinno byc AggregateUTXO
