### ISSUE TITLE
EncQR Code Backup problem

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#28]
Konto importowane z seeda, nie da się wygenerować EncQR w najnowszej wersji programu, w 0.4.0 daje radę.

![bandicam20190311112950408](https://user-images.githubusercontent.com/45454639/54121302-6791bc80-43fa-11e9-8510-e3badfce58de.gif)

**Comment by zurekpiotr** [comment]
Problem u mnie nie występuje  
Nie wiem co może go powodować

**Comment by Fl4reTobiasH** [comment]
@zurekpiotr  Być może ma to związek z tym że odpalam program z domyślnej lokalizacji instalacji %appdata%/hodlertech/ a nie z pulpitu

**Comment by Fl4reTobiasH** [comment]
@zurekpiotr Daj znać czy po powyższej wskazówce udało Ci się odtworzyć błąd.
