### ISSUE TITLE
Crash aplikacji Windows po uruchomieniu czytnika QR 

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#29]

**Comment by tendersoft-mjb** [comment]
u mnie całkowity brak formatki czytnika (v. 0.4.0.Win32)
![2019-03-11 (3)](https://user-images.githubusercontent.com/7294417/54137238-91100f80-441d-11e9-982d-ee5f6bc4b54f.png)
Na prawej krawędzi jest jakaś kropeczka, która zmienia kursor na 'resize', ale jest to nieklikalne i nic się nie rozszerza - o co chodzi?

**Comment by zurekpiotr** [comment]
Ta kropeczka powinna być pomiędzy widokiem z listą coinów a widokiem szczegółowym 
Służy do zmiany wielkości tych dwóch części aplikacji

**Comment by zurekpiotr** [comment]
![image](https://user-images.githubusercontent.com/26895661/54138462-d2092380-441f-11e9-96aa-2ca3e202fa10.png)
![image](https://user-images.githubusercontent.com/26895661/54138488-de8d7c00-441f-11e9-9712-42e345b32e41.png)

**Comment by Fl4reTobiasH** [comment]
Co było nie tak z czytnikiem? Kto go popsuł?

**Comment by zurekpiotr** [comment]
przy tworzeniu ciemnej obwódki odwoływałem się do piksela poza obrazem
