### ISSUE TITLE
Salda są wyświetlane w mylący sposób

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#36]
![image](https://user-images.githubusercontent.com/45454639/54309783-23a4e000-45d1-11e9-9abb-9a92d62ee148.png)

Jeśli coś wysyłam, pokazuje się w niepotwierdzonych, powinno zniknąć z Balance

**Comment by DanielMazurFL4RE** [comment]
To w tym wyswietlaniu niech od razu uwzgledni kod fakeblockchain od nano, bo fiaty sie nie odliczaja.
https://github.com/Fl4reTobiasH/HDL/issues/35

**Comment by Fl4reTobiasH** [comment]
@DanielMazurFL4RE 
możesz jaśniej, bardziej opisowo,  by mój ograniczony umysł był w stanie ogarnąć twój geniusz?;)

**Comment by zurekpiotr** [comment]
Obecnie API zwraca unconfirmed już zsumowane ( jako wychodzące i przychodzące ).
Nie jestem w stanie pokazać prawidłowej kwoty oczekujących ( np. przychodzi 1 LTC a wychodzi 2 
więc API zwróci -1      
jak wyświetlę 0 będzie przekłamywać )
Przydało by się żeby API zwracało unconfirmedIN i unconfirmedOUT 
albo listę niepotwierdzonych transakcji
