### ISSUE TITLE
NANO LINUX - Problem z transakcjami wychodzącymi

### ISSUE THREAD

**Issue by Fl4reTobiasH** [Fl4reTobiasH/HDL#42]
Transakcje przychodzące nie są wydobywane w aplikacji Linux, saldo pokazuje się w polu potwierdzonych transakcji jednak w nano explorer transakcja jest niepotwierdzona. Po restarcie, związku z błędem który powoduje że saldo jest potwierdzone, można nadać transakcję niepotwierdzoną jednak powoduje ona błąd w postaci wyświetlenia w portfelu nadawczym salda z portfela odbiorczego, a następnie środki znikają z sald portfela.

**Comment by Fl4reTobiasH** [comment]
Exception EAccessViolation in module hodler at 000000000044C76D.
Access violation at address 000000000044C76D, accessing address 0000000000000000.
Segmentation fault (core dumped)

po tym jak nano z portfela docelowego pojawiło się w źródłowym

https://www.nanode.co/account/xrb_1qghgkffdf7qcei9xj1tiye36ch1nyzbiik55ajhuarssoqmbt8qjn43ydj3

powyżej adres źródłowy transakcji wychodzącej na linuksie

**Comment by tendersoft-mjb** [comment]
Kurde, za dużo mamy tych grubych błędów - czas zatrudnić jakiegoś testera, żeby zestawił środowisko do auto-testów przy każdym buildzie typu release.

**Comment by DanielMazurFL4RE** [comment]
Testuja chłopaki na linuksie

**Comment by Fl4reTobiasH** [comment]
@tendersoft-mjb to własnie info od testerów niepublicznej bety Linuksa

**Comment by DanielMazurFL4RE** [comment]
Przyczyna: odpalenie hodlera przez ikonke sprawia ze nie znajduje on procesu nanopow64, odpalenie z konsoli poprzez ./hodler odpala koparke

**Comment by Fl4reTobiasH** [comment]
Sprawdzę to, dzięki. Super że to taki drobiazg.

**Comment by tendersoft-mjb** [comment]
Co było problemem, inna domyślna ścieżka uruchomieniowa/dla komponentów w zależności od tego, w jaki sposób był uruchamiany Hodler?
